index:
    path: /
    controller: App\Controller\ScheduleController::indexAction
teacherDownload:
    path: /teacher-download
    controller: App\Controller\ApiDataController::teacherDownloadAction
roomDownload:
    path: /room-download
    controller: App\Controller\ApiDataController::roomDownloadAction
subjectDownload:
    path: /subject-download
    controller: App\Controller\ApiDataController::subjectDownloadAction
groupDownload:
    path: /group-download
    controller: App\Controller\ApiDataController::groupDownloadAction
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
