index:
    path: /
    controller: App\Controller\ScheduleController::indexAction
teacherDownload:
    path: /teacher-download
    controller: App\Controller\ApiDataController::teacherDownloadAction
roomDownload:
    path: /room-download
    controller: App\Controller\ApiDataController::roomDownloadAction
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
